# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true
sections: true

title_template: "Timbuctu arch / %s"
og_image: /img/og_emma.png
author: Timbuctu arch
favicon: /img/favicon.svg
description: Minimalist, designer, and UX developer
port: 8083

# OG image
origin: https://simple-blog.nuejs.org
og: /img/og.jpg


navigation:
  header:
    - Timbuctu arch: /
    - Contact: /contact/

  footer:
    - © Timbuctu arch: /

    - image: /img/twitter.svg
      url: //x.com/tipiirai
      alt: Twitter (X) profile
      size: 22 x 22

    - image: /img/github.svg
      url: //github.com/nuejs/nue/
      alt: Github Projects
      size: 22 x 22

    - image: /img/linkedin.svg
      url: //linkedin.com/in/tipiirai
      alt: LinkedIn profile
      size: 22 x 22
